// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_NumTemperature;
extern lv_obj_t * ui_labCelsius;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_ButtonStart;
extern lv_obj_t * ui_labBattery;
extern lv_obj_t * ui_labPressureBottom;
extern lv_obj_t * ui_NumPressureBottom;
extern lv_obj_t * ui_labUserTemp;
extern lv_obj_t * ui_NumUserTemp;
extern lv_obj_t * ui_searching;
extern lv_obj_t * ui_connected;
extern lv_obj_t * ui_default;
extern lv_obj_t * ui_batterylevel;
extern lv_obj_t * ui_mainpower;
extern lv_obj_t * ui_forest;
extern lv_obj_t * ui_ocean;
// CUSTOM VARIABLES
extern lv_obj_t * uic_MainScreen;
extern lv_obj_t * uic_default;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_searching_png);    // assets/searching.png
LV_IMG_DECLARE(ui_img_connected_png);    // assets/connected.png
LV_IMG_DECLARE(ui_img_default_png);    // assets/default.png
LV_IMG_DECLARE(ui_img_electric_png);    // assets/electric.png
LV_IMG_DECLARE(ui_img_forest_png);    // assets/forest.png
LV_IMG_DECLARE(ui_img_ocean_png);    // assets/ocean.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
