// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_NumTemperature;
extern lv_obj_t * ui_labCelsius;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_ButtonStart;
extern lv_obj_t * ui_labBattery;
extern lv_obj_t * ui_labPressureBottom;
extern lv_obj_t * ui_labPressureTop;
extern lv_obj_t * ui_NumBattery;
extern lv_obj_t * ui_NumPressureTop;
extern lv_obj_t * ui_NumPressureBottom;
extern lv_obj_t * ui_labUserTemp;
extern lv_obj_t * ui_NumUserTemp;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
