// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temperature = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature, -20);
    lv_obj_set_y(ui_temperature, -79);
    lv_obj_set_align(ui_temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperature, "Temperature");

    ui_temperatureNumber = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temperatureNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperatureNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperatureNumber, -20);
    lv_obj_set_y(ui_temperatureNumber, -9);
    lv_obj_set_align(ui_temperatureNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperatureNumber, "0");

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -20);
    lv_obj_set_y(ui_Label3, 22);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Celsius ");

    ui_uiTemperatureGauge = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_uiTemperatureGauge, 125);
    lv_obj_set_height(ui_uiTemperatureGauge, 150);
    lv_obj_set_x(ui_uiTemperatureGauge, -20);
    lv_obj_set_y(ui_uiTemperatureGauge, 14);
    lv_obj_set_align(ui_uiTemperatureGauge, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_uiTemperatureGauge, 50);


    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 92);
    lv_obj_set_height(ui_Button1, 33);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, 83);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x1BC47E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -1);
    lv_obj_set_y(ui_Label4, 85);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Play");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_using_battery_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image3, 70);
    lv_obj_set_y(ui_Image3, -6);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_using_main_power_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image4, 81);
    lv_obj_set_y(ui_Image4, -6);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
