// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperature = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature, 1);
    lv_obj_set_y(ui_temperature, -94);
    lv_obj_set_align(ui_temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperature, "Water\nTemperature");
    lv_obj_set_style_text_color(ui_temperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_temperature, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumTemperature = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_NumTemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumTemperature, 1);
    lv_obj_set_y(ui_NumTemperature, -40);
    lv_obj_set_align(ui_NumTemperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumTemperature, "0");
    lv_obj_set_style_text_color(ui_NumTemperature, lv_color_hex(0xEBCC1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NumTemperature, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labCelsius = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labCelsius, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labCelsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labCelsius, 61);
    lv_obj_set_y(ui_labCelsius, -62);
    lv_obj_set_align(ui_labCelsius, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labCelsius, "°C");
    lv_obj_set_style_text_color(ui_labCelsius, lv_color_hex(0x9AD8B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labCelsius, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labCelsius, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 92);
    lv_obj_set_height(ui_Button1, 33);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, 83);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x1BC47E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonStart = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonStart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonStart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ButtonStart, -1);
    lv_obj_set_y(ui_ButtonStart, 85);
    lv_obj_set_align(ui_ButtonStart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonStart, "Start");
    lv_obj_set_style_text_color(ui_ButtonStart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonStart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labBattery = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labBattery, 0);
    lv_obj_set_y(ui_labBattery, 14);
    lv_obj_set_align(ui_labBattery, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labBattery, "Battery");
    lv_obj_set_style_text_color(ui_labBattery, lv_color_hex(0x2EFEEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labBattery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labBattery, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labPressureBottom = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labPressureBottom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labPressureBottom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labPressureBottom, 84);
    lv_obj_set_y(ui_labPressureBottom, 23);
    lv_obj_set_align(ui_labPressureBottom, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labPressureBottom, "P.Bott");
    lv_obj_set_style_text_color(ui_labPressureBottom, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labPressureBottom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labPressureTop = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labPressureTop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labPressureTop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labPressureTop, -78);
    lv_obj_set_y(ui_labPressureTop, 23);
    lv_obj_set_align(ui_labPressureTop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labPressureTop, "P.Top");
    lv_obj_set_style_text_color(ui_labPressureTop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labPressureTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumBattery = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_NumBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumBattery, -1);
    lv_obj_set_y(ui_NumBattery, 43);
    lv_obj_set_align(ui_NumBattery, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumBattery, "0");
    lv_obj_set_style_text_color(ui_NumBattery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumBattery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NumBattery, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumPressureTop = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_NumPressureTop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumPressureTop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumPressureTop, -78);
    lv_obj_set_y(ui_NumPressureTop, 46);
    lv_obj_set_align(ui_NumPressureTop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumPressureTop, "0");
    lv_obj_set_style_text_color(ui_NumPressureTop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumPressureTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumPressureBottom = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_NumPressureBottom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumPressureBottom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumPressureBottom, 83);
    lv_obj_set_y(ui_NumPressureBottom, 43);
    lv_obj_set_align(ui_NumPressureBottom, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumPressureBottom, "0");
    lv_obj_set_style_text_color(ui_NumPressureBottom, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumPressureBottom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labUserTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labUserTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labUserTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labUserTemp, -75);
    lv_obj_set_y(ui_labUserTemp, -52);
    lv_obj_set_align(ui_labUserTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labUserTemp, "User\nTemp");
    lv_obj_set_style_text_color(ui_labUserTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labUserTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labUserTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labUserTemp, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumUserTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_NumUserTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumUserTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumUserTemp, -77);
    lv_obj_set_y(ui_NumUserTemp, -19);
    lv_obj_set_align(ui_NumUserTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumUserTemp, "0");
    lv_obj_set_style_text_color(ui_NumUserTemp, lv_color_hex(0x1A9CC2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumUserTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


}
